Login&RegistroC#/MVC/Models/ErrorViewModel.cs
namespace MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Login&RegistroC#/MVC/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;


namespace MVC.Models
{
    public class LoginModel
    {

        [Required(ErrorMessage = "Campo requerido")]
        public string? Usuario { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        public string? Clave { get; set; }
    }
}

Login&RegistroC#/MVC/Models/UsuarioModel.cs
//Este modelo servira para llenar los datos al momento del registro o llamar cierta informacion de un usuario
//Porque se va aplicar restrinciones al momento de hacer algun submit en los botones tanto de registrarse como de login
using System.ComponentModel.DataAnnotations;


namespace MVC.Models
{
    public class UsuarioModel
    {

        //Vamos a identificarlos
        [Key] //primarykey
        //Definimos propiedades
        public int Id_Usuario { get; set; }

        [Required(ErrorMessage = "Campo requerido")] // pues esto es para identificar cada unos de los campos y son requeridos
        public string? Nombre { get; set; } // se identifica que estas propiedades van a aceptar valores nulos
                                            // al final uno se asegura que no inserten valores nulos atraves de las validaciones. 

        [Required(ErrorMessage = "Campo requerido")]
        public string? Correo { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        public int Edad { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        public string? Usuario { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        public string? Clave { get; set; }
    }
}


// Tenemos en UsuarioModel que va estar para almacenar los datos o valores  que se vayan a estar registrando o obtener la informacion de
// algun usuario que querramis obtener 

Login&RegistroC#/MVC/Controllers/CuentaController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Data;
using MVC.Models;
using System.Data;
using System.Data.SqlClient;

namespace MVC.Controllers
{
    public class CuentaController : Controller
    {
        private readonly DbContext _contexto; // se agrego una variable privada de solo lectura

        public CuentaController(DbContext contexto)
        {
            _contexto = contexto; // se va a hacer una igualdad de los parametros

        }

        public ActionResult Registrar()
        {
            return View("Registrar");
        }

        [HttpPost]
        public ActionResult Registrar(UsuarioModel u) // El UsuarioModel tiene el valor de u, que se le da a este metodo
        {

            try
            {
                //Aaqui agregaremos los procedimientos almacenados
                //Validar que mi modelo usuario esta correcto
                if (ModelState.IsValid)
                {
                    using (SqlConnection con = new(_contexto.Valor))
                    {
                        using (SqlCommand cmd = new("sp_registrar", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure; //CommandType es un procedimiento almacenado
                            cmd.Parameters.Add("@Nombre", SqlDbType.VarChar).Value = u.Nombre;
                            cmd.Parameters.Add("@Correo", SqlDbType.VarChar).Value = u.Correo;
                            cmd.Parameters.Add("@Edad", SqlDbType.Int).Value = u.Edad;
                            cmd.Parameters.Add("@Usuario", SqlDbType.VarChar).Value = u.Usuario;
                            cmd.Parameters.Add("@Clave", SqlDbType.VarChar).Value = u.Clave;
                            con.Open(); // La abrimos 
                            cmd.ExecuteNonQuery(); // ejecutamos el procedimiento
                            con.Close();
                        }
                    }

                    return RedirectToAction("Index", "Home"); // Returnar la vista index de mi controlador home



                }

            }
            catch (Exception)
            {
                return View("Registrar");

            }

            ViewData["error"] = "Error de credenciales";
            return View("Registrar");

        }



        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        public ActionResult Login(LoginModel l)
        {
            try
            {
                //Aaqui agregaremos los procedimientos almacenados
                //Validar que mi modelo usuario esta correcto
                if (ModelState.IsValid)
                {
                    using (SqlConnection con = new(_contexto.Valor))
                    {
                        using (SqlCommand cmd = new("sp_login", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure; //CommandType es un procedimiento almacenado
                            cmd.Parameters.Add("@Usuario", SqlDbType.VarChar).Value = l.Usuario;
                            cmd.Parameters.Add("@Clave", SqlDbType.VarChar).Value = l.Clave;
                            con.Open(); // La abrimos 

                            SqlDataReader dr = cmd.ExecuteReader(); // procedimiento almacenado 

                            if (dr.Read())
                            {
                                //en el caso que se obtengan valores vamos a redireccionar al usuario 
                                Response.Cookies.Append("user", "Bienvenido " + l.Usuario); // Al crear esta cookie se almacena solo un mensaje de bienvenida
                                //Se va crear una cookie donde se almacenara el valor de 
                                return RedirectToAction("Index", "Home");

                            }
                            else
                            {
                                ViewData["error"] = "Error de credenciales";
                            }


                            con.Close();
                        }
                    }

                    return RedirectToAction("Index", "Home"); // Returnar la vista index de mi controlador home



                }

            }
            catch (Exception)
            {
                return View("Login");

            }


            return View("Login");

        }



        public ActionResult Logout()
        {
            Response.Cookies.Delete("user");
            return RedirectToAction("Index", "Home"); // A la vista Index del controlador Home
        }



    }
}

Login&RegistroC#/MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        ViewData["usuario"] = Request.Cookies["user"];
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Login&RegistroC#/MVC/Views/Cuenta/Login.cshtml
@model LoginModel

@{
    ViewBag.Title = "Iniciar";
}

<form method="post">
    <div class="container register">
        <div class="row">
            <div class="col-md-3 register-left">
                <div class="col-md-9 register-right"></div>
                <div class="tab-content">
                    <div class="col-md-6">
                        <div class="form-group">
                            <span asp-validation-for="Usuario" class="text-danger"></span>
                            <input asp-for="Usuario" class="form-control" placeholder="Usuario" type="text">
                        </div>
                        <br>
                        <div class="form-group">
                            <span asp-validation-for="Clave" class="text-danger"></span>
                            <input asp-for="Clave" class="form-control" placeholder="Password" type="password">
                        </div>
                    </div>
                    <br>
                    <div class="col-md-6">
                        <input type="submit" value="Log in" class="btn btn-primary" asp-action="Login"
                            asp-controller="Cuenta">
                    </div>
                </div>
            </div>


        </div>

    </div>

</form>

Login&RegistroC#/MVC/Views/Cuenta/Registrar.cshtml
@model UsuarioModel

@{
    ViewBag.Title = "Registrarse";
}

<form method="post">
    <div class="container register">
        <div class="row">
            <div class="col-md-3 register-left">
                <div class="col-md-9 register-right"></div>
                <div class="tab-content">
                    <div class="col-md-6">
                        <div class="form-group">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                            <input asp-for="Nombre" class="form-control" placeholder="Nombre" type="text">
                        </div>
                        <br>
                        <div class="form-group">
                            <span asp-validation-for="Correo" class="text-danger"></span>
                            <input asp-for="Correo" class="form-control" placeholder="Email" type="email">
                        </div>
                        <br>
                        <div class="form-group">
                            <span asp-validation-for="Edad" class="text-danger"></span>
                            <input asp-for="Edad" class="form-control" placeholder="Edad" type="text">
                        </div>
                        <br>
                        <div class="form-group">
                            <span asp-validation-for="Usuario" class="text-danger"></span>
                            <input asp-for="Usuario" class="form-control" placeholder="Usuario" type="text">
                        </div>
                        <br>
                        <div class="form-group">
                            <span asp-validation-for="Clave" class="text-danger"></span>
                            <input asp-for="Clave" class="form-control" placeholder="Password" type="password">
                        </div>
                    </div>
                    <br>
                    <div class="col-md-6">
                        <input type="submit" value="Registrarse" class="btn btn-primary" asp-action="Registrar"
                            asp-controller="Cuenta">
                    </div>
                </div>
            </div>


        </div>

    </div>

</form>

Login&RegistroC#/MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["usuario"]</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Login&RegistroC#/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta"
                                asp-action="Registrar">Registrarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta"
                                asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta"
                                asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>